delete from public.organizations;
insert into public.organizations (name,category,country,mission,url,email,logo,status,sort) values
('Association Tin Hinan','women','bf','{"en":"Rights of indigenous women & pastoral communities of the Sahel","fr":"Droits des femmes autochtones & communautés pastorales du Sahel","es":"Derechos de las mujeres indígenas y comunidades pastoriles del Sahel"}'::jsonb,'http://www.tin-hinane.org',null,null,'approved',0),
('AFPAT','women','td','{"en":"Association of Peul Women & Autochthonous Peoples of Chad — climate & rights advocacy","fr":"Association des Femmes Peules et Peuples Autochtones du Tchad — plaidoyer climat & droits","es":"Asociación de Mujeres Peul y Pueblos Autóctonos de Chad — defensa climática y de derechos"}'::jsonb,'https://afpat.net',null,null,'approved',1),
('FIMI / IIWF','women','pe','{"en":"International Indigenous Women''s Forum — global network and observatory","fr":"Forum international des femmes autochtones — réseau mondial et observatoire","es":"Foro Internacional de Mujeres Indígenas — red mundial y observatorio"}'::jsonb,'https://fimi-iiwf.org',null,null,'approved',2),
('Global Indigenous Youth Caucus','youth','int','{"en":"Youth voice within the UN Permanent Forum (UNPFII)","fr":"La voix des jeunes au sein de l''Instance permanente de l''ONU (UNPFII)","es":"La voz de la juventud en el Foro Permanente de la ONU (UNPFII)"}'::jsonb,'https://www.globalindigenousyouthcaucus.org',null,null,'approved',3),
('GYBN','youth','de','{"en":"Global Youth Biodiversity Network — youth engagement in the CBD, incl. indigenous youth","fr":"Réseau mondial de la jeunesse pour la biodiversité — engagement dans la CDB, dont jeunes autochtones","es":"Red Mundial de Juventud por la Biodiversidad — participación en el CDB, incl. juventud indígena"}'::jsonb,'https://gybn.org',null,null,'approved',4),
('WAMIP','pastoral','int','{"en":"World Alliance of Mobile Indigenous Peoples — global pastoralist alliance","fr":"Alliance mondiale des peuples autochtones mobiles — alliance pastorale mondiale","es":"Alianza Mundial de Pueblos Indígenas Móviles — alianza pastoril mundial"}'::jsonb,'https://wamipglobal.com',null,null,'approved',5),
('Réseau Billital Maroobé','pastoral','ne','{"en":"West African network of pastoralist organizations — transhumance & markets","fr":"Réseau ouest-africain des organisations d''éleveurs — transhumance & marchés","es":"Red de África Occidental de organizaciones de pastores — trashumancia y mercados"}'::jsonb,'https://maroobe.com',null,null,'approved',6),
('IWGIA','gen','dk','{"en":"Documentation & advocacy — publishes The Indigenous World","fr":"Documentation & plaidoyer — publie The Indigenous World","es":"Documentación y defensa — publica El Mundo Indígena"}'::jsonb,'https://www.iwgia.org',null,null,'approved',7),
('Cultural Survival','gen','us','{"en":"Advocacy, community radio & grants (Keepers of the Earth Fund)","fr":"Plaidoyer, radios communautaires & subventions (Keepers of the Earth Fund)","es":"Defensa, radios comunitarias y subvenciones (Keepers of the Earth Fund)"}'::jsonb,'https://www.culturalsurvival.org',null,null,'approved',8),
('IPACC','gen','za','{"en":"Coordinating committee of ~135 African indigenous organizations","fr":"Comité de coordination d''environ 135 organisations autochtones africaines","es":"Comité coordinador de ~135 organizaciones indígenas africanas"}'::jsonb,'https://www.ipacc.org.za',null,null,'approved',9),
('AIPP','gen','th','{"en":"Asia Indigenous Peoples Pact — regional alliance","fr":"Asia Indigenous Peoples Pact — alliance régionale","es":"Asia Indigenous Peoples Pact — alianza regional"}'::jsonb,'https://aippnet.org',null,null,'approved',10),
('COICA','gen','ec','{"en":"Coordination of indigenous organizations of the Amazon basin","fr":"Coordination des organisations autochtones du bassin amazonien","es":"Coordinación de organizaciones indígenas de la cuenca amazónica"}'::jsonb,'https://coicamazonia.org',null,null,'approved',11),
('Saami Council','gen','no','{"en":"Voluntary Sámi organization across four countries","fr":"Organisation sámi volontaire couvrant quatre pays","es":"Organización sami voluntaria en cuatro países"}'::jsonb,'https://www.saamicouncil.net',null,null,'approved',12);

delete from public.news;
insert into public.news (day,month,source,title,body,published,sort) values
('02','{"en":"JUL","fr":"JUIL","es":"JUL"}'::jsonb,'{"en":"IYRP / FAO","fr":"IYRP / FAO","es":"IYRP / FAO"}'::jsonb,'{"en":"IYRP 2026: regional rangelands consultations continue across the Sahel","fr":"IYRP 2026 : les consultations régionales sur les parcours se poursuivent au Sahel","es":"IYRP 2026: continúan las consultas regionales sobre pastizales en el Sahel"}'::jsonb,'{"en":"The International Year of Rangelands and Pastoralists mobilizes pastoral networks around mobility rights and land tenure.","fr":"L''Année internationale des parcours et des pasteurs mobilise les réseaux pastoraux autour des droits de mobilité et du foncier.","es":"El Año Internacional de los Pastizales moviliza a las redes pastoriles en torno a la movilidad y la tenencia de tierras."}'::jsonb,true,0),
('24','{"en":"JUN","fr":"JUIN","es":"JUN"}'::jsonb,'{"en":"Academic review","fr":"Revue académique","es":"Revista académica"}'::jsonb,'{"en":"Green transition and pastoral lands: new research maps land-acquisition pressures","fr":"Transition verte et terres pastorales : de nouvelles recherches cartographient les pressions foncières","es":"Transición verde y tierras pastoriles: nuevas investigaciones mapean las presiones sobre la tierra"}'::jsonb,'{"en":"Peer-reviewed work documents how renewable-energy projects overlap customary pastoral territories.","fr":"Des travaux évalués par les pairs documentent le chevauchement entre projets d''énergies renouvelables et territoires pastoraux coutumiers.","es":"Trabajos revisados por pares documentan la superposición de proyectos de energía renovable con territorios pastoriles consuetudinarios."}'::jsonb,true,1),
('15','{"en":"JUN","fr":"JUIN","es":"JUN"}'::jsonb,'{"en":"UN DESA","fr":"UN DESA","es":"UN DESA"}'::jsonb,'{"en":"UNPFII follow-up: recommendations on indigenous data governance","fr":"Suivi de l''UNPFII : recommandations sur la gouvernance des données autochtones","es":"Seguimiento del UNPFII: recomendaciones sobre gobernanza de datos indígenas"}'::jsonb,'{"en":"The Permanent Forum reiterates support for CARE principles in national statistics and research.","fr":"L''Instance permanente réitère son soutien aux principes CARE dans les statistiques nationales et la recherche.","es":"El Foro Permanente reitera su apoyo a los principios CARE en las estadísticas nacionales y la investigación."}'::jsonb,true,2);

delete from public.opportunities;
insert into public.opportunities (title,body,deadline,published,sort) values
('{"en":"New Commons Incubator — Indigenous Languages & Cultures","fr":"New Commons Incubator — Langues et cultures autochtones","es":"New Commons Incubator — Lenguas y culturas indígenas"}'::jsonb,'{"en":"Funding and support for digital commons projects led by or with indigenous communities.","fr":"Financement et accompagnement de projets de communs numériques portés par ou avec des communautés autochtones.","es":"Financiación y apoyo a proyectos de comunes digitales liderados por o con comunidades indígenas."}'::jsonb,'{"en":"Deadline: 31 July 2026","fr":"Date limite : 31 juillet 2026","es":"Fecha límite: 31 de julio de 2026"}'::jsonb,true,0),
('{"en":"3rd UN Global Indigenous Youth Forum (UNGIYF)","fr":"3e Forum mondial de la jeunesse autochtone des Nations Unies (UNGIYF)","es":"3er Foro Mundial de la Juventud Indígena de la ONU (UNGIYF)"}'::jsonb,'{"en":"FAO-hosted global forum for indigenous youth on food systems and climate.","fr":"Forum mondial accueilli par la FAO pour la jeunesse autochtone : systèmes alimentaires et climat.","es":"Foro mundial organizado por la FAO para la juventud indígena: sistemas alimentarios y clima."}'::jsonb,'{"en":"Call open — check eligibility","fr":"Appel ouvert — vérifier l''éligibilité","es":"Convocatoria abierta — verificar elegibilidad"}'::jsonb,true,1),
('{"en":"World Heritage training for Indigenous representatives","fr":"Formation Patrimoine mondial pour représentants autochtones","es":"Formación en Patrimonio Mundial para representantes indígenas"}'::jsonb,'{"en":"Organized by IIPFWH, Nia Tero, IWGIA, DOCIP and OHCHR.","fr":"Organisée par l''IIPFWH, Nia Tero, IWGIA, DOCIP et le HCDH.","es":"Organizada por IIPFWH, Nia Tero, IWGIA, DOCIP y ACNUDH."}'::jsonb,'{"en":"Applications open","fr":"Candidatures ouvertes","es":"Solicitudes abiertas"}'::jsonb,true,2),
('{"en":"Pawanka Fund — community grants","fr":"Fonds Pawanka — subventions communautaires","es":"Fondo Pawanka — subvenciones comunitarias"}'::jsonb,'{"en":"Indigenous-led fund supporting traditional knowledge and wellbeing initiatives.","fr":"Fonds dirigé par des autochtones soutenant les savoirs traditionnels et le bien-être.","es":"Fondo dirigido por indígenas que apoya los conocimientos tradicionales y el bienestar."}'::jsonb,'{"en":"Rolling basis","fr":"Au fil de l''eau","es":"Convocatoria continua"}'::jsonb,true,3);
